apiVersion: apps/v1
kind: Deployment
metadata:
  name: rallylite-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rallylite-backend
  template:
    metadata:
      labels:
        app: rallylite-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/amirchaaari/rallylite-backend:latest
        ports:
        - containerPort: 3000
